### ISSUE TITLE
Implement English scripts

### ISSUE THREAD

**Issue by reinzanini** [wetor/ONScripter-jh-Switch#2]
Would it be possible to implement in some way English scripts? Random guess here, but I think that the problem lays with the "line delimiter". In fact, when given English scripts, the homebrew gives as text lines with Japanese characters and often various "`". which are usually the delimiter for scripts in English.

**Comment by wetor** [comment]
Yes, of course. But now my switch is not around, so I can't support it. Can you provide an English game?

**Comment by reinzanini** [comment]
Higanbana or Rose Guns Days, please.

**Comment by brandon-dodds** [comment]
Has any progress been made towards this?

**Comment by wetor** [comment]
@reinzanini  @brandon-dodds 
Now it is supported (V2.0.1), just set ONSBrowser language to English !

By the way, some old game video formats may not be supported. If there is an error, please delete the video file.

Enjoy yourself
