### ISSUE TITLE
12.0.0系统下已经无法运行

### ISSUE THREAD

**Issue by ayssia** [wetor/ONScripter-jh-Switch#4]
系统固件12.0.0（大气层0.19.1）下已经无法运行，一旦运行就会报2144-0001。

**Comment by ayssia** [comment]
尝试在最新版libnx下编译，发现没有lua库……

```
In file included from E:/repos/ons/ONScripter-jh-Switch/include/ONScripter.h:28,
                 from E:/repos/ons/ONScripter-jh-Switch/source/onscripter/onscripter_main.cpp:25:
E:/repos/ons/ONScripter-jh-Switch/include/ScriptParser.h:40:10: fatal error: LUAHandler.h: No such file or directory
   40 | #include "LUAHandler.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: onscripter_main.o] Error 1
make: *** [Makefile:220: build] Error 2
```

用pacman看了一下似乎libnx里就没有lua库……

**Comment by huimeilongyin** [comment]
那是不是就不能用了呀

**Comment by wetor** [comment]
lua库在这里 https://github.com/carstene1ns/lua51-switch
当时发布时也没想有人会去折腾，所以编译相关的问题也都没提。。。
至于12.0运行问题，你可以先排除一下是否为GUI问题，此项目编译出的nro是不含GUI的

**Comment by ayssia** [comment]
> 
> 
> lua库在这里 https://github.com/carstene1ns/lua51-switch
> 当时发布时也没想有人会去折腾，所以编译相关的问题也都没提。。。
> 至于12.0运行问题，你可以先排除一下是否为GUI问题，此项目编译出的nro是不含GUI的

GUI和本体运行都会崩溃。

**Comment by wetor** [comment]
mouse_png_xxx这些其实是/data/mouse.png这个资源的数据和属性，在以前，makefile编译png时会放到替换mouse_png.h中。

具体忘了是那个库的功能了，现在可能变了，这只是一个鼠标的指针而已，如果找不到makefile的解决方法，可以把这个图像的二进制数据直接放到mouse_png.h中

PS:我好像没收邮件提醒，又因为你是编辑的我看回复数没加就没点进来看= =下次直接回复就行

**Comment by wetor** [comment]
@ayssia  @huimeilongyin 
12.0已经支持了
