### ISSUE TITLE
English novels works but weird

### ISSUE THREAD

**Issue by JrRadiant** [wetor/ONScripter-jh-Switch#6]
Konnichiwa, dear wetor-san! Thanks for your nice project!..

I tried some English novels, many doesn't work (crashing with error at start) but the one, Narcissu (it's officially freeware here: http://narcissu.gwathyr.net/) works good except of the non-readable text like this:

![sample](https://user-images.githubusercontent.com/61790774/124376262-ef84ea00-dcc7-11eb-8772-32a214762b39.jpg)

Could you be so kind to fix it in the next ONScripter-jh-Switch release?

Thank you in advance!

**Comment by wetor** [comment]
Now it is supported (V2.0.1), just set ONSBrowser language to English !

By the way, some old game video formats may not be supported. If there is an error, please delete the video file.

Enjoy yourself
